[package]
name = "testpilot"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
csv = "1.3"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
toml = "0.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
msfs = { git = "https://github.com/flybywiresim/msfs-rs", branch = "main" }

[profile.release]
lto = true
strip = true
