[package]
name = "testpilot"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
testpilot-core.workspace = true
testpilot-msfs.workspace = true
testpilot-a32nx.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
msfs.workspace = true

[dev-dependencies]
criterion.workspace = true

[lints]
workspace = true

[[bench]]
name = "hot_path"
harness = false
